refactor: Переименуй фотографии #4
Bo4kaa/work_1 pull request #28
Opened 2023-09-14 16:10 UTC by Bo4kaa

- Fix #4

2023-09-14 16:11 UTC, Bo4kaa commented
там крч платформы для прослушивания их 5шт вроде я ток спотик и саунд знаю остальные не ебу как называются))

2023-09-14 16:32 UTC, f4lz reviewed
Сами фотки, в файлах

2023-09-14 16:36 UTC, f4lz commented
> там крч платформы для прослушивания их 5шт вроде я ток спотик и саунд знаю остальные не ебу как называются))
> 
> 

ты поменял альты у фоток, а надо сами фото))

2023-09-15 11:46 UTC, f4lz requested changes

2023-09-15 11:46 UTC, f4lz commented on img/Frame (1).png
Без пробелов, можешь поставить "-"

2023-09-15 11:46 UTC, f4lz commented on img/Jacob Paulaner.png
Без пробелов, можешь поставить "-"

2023-09-15 12:12 UTC, f4lz approved these changes

2023-09-15 12:12 UTC, merged