Сделай звездочки svg #7
Bo4kaa/work_1 pull request #38
Opened 2023-09-18 12:05 UTC by Bo4kaa

походу чет не помогло

2023-09-18 12:13 UTC, f4lz requested changes
Не как фотки попробуй, а как код svg

2023-09-18 12:25 UTC, Bo4kaa commented
типо просто скопировать код и в имг вставить?

2023-09-18 12:26 UTC, f4lz commented
> типо просто скопировать код и в имг вставить?

Не в img, ща

2023-09-18 12:29 UTC, f4lz requested changes
Вот так

2023-09-18 12:29 UTC, f4lz commented on index.html
> +                    <img src="img/STAR.svg" alt="star">
```suggestion
                   <svg width="18" height="17" viewBox="0 0 18 17" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M9.01265 14.135L13.1626 16.645C13.9226 17.105 14.8526 16.425 14.6526 15.565L13.5526 10.845L17.2226 7.665C17.8926 7.085 17.5326 5.985 16.6526 5.915L11.8226 5.505L9.93265 1.045C9.59265 0.235 8.43265 0.235 8.09265 1.045L6.20265 5.495L1.37265 5.905C0.492646 5.975 0.132646 7.075 0.802646 7.655L4.47265 10.835L3.37265 15.555C3.17265 16.415 4.10265 17.095 4.86265 16.635L9.01265 14.135Z" fill="#FCFF51"/>
</svg>

```

2023-09-18 12:36 UTC, f4lz commented
> походу чет не помогло

Замени этот текст на

 - Fix #7

2023-09-18 13:13 UTC, Bo4kaa commented
я крч забыл куда fix писать((((

2023-09-18 13:14 UTC, Bo4kaa commented
точнее вроде вспомнил но когда заливаб то забываю про него

2023-09-20 12:18 UTC, f4lz commented
> > походу чет не помогло
> 
> Замени этот текст на
> 
> * Fix [Сделай звездочки `svg` #7](https://github.com/Bo4kaa/work_1/issues/7)



 - Fix #7

2023-09-20 12:19 UTC, merged

2023-09-20 12:21 UTC, Bo4kaa commented
не пон я же написал " - Fix #7"

2023-09-20 12:21 UTC, Bo4kaa commented
разве не так?