переиновал_блоки#8
Bo4kaa/work_1 pull request #60
Opened 2023-10-03 20:28 UTC by Bo4kaa

- Fix #8

2023-10-03 22:03 UTC, f4lz requested changes

2023-10-03 22:03 UTC, f4lz commented on index.html
>                  <p>He’s here to help you level up your game by sharing everything he’s learned along the way.</p>
Придумай название этому блоку, типо портфолио `portfolio` или что-то в этом роде

2023-10-03 22:03 UTC, f4lz commented on index.html
>                  <p>He’s here to help you level up your game by sharing everything he’s learned along the way.</p>
Ну и в соответствии переделай

2023-10-03 22:03 UTC, f4lz commented on index.html
>              </div>
Лучше назвать типо `form` и поменять `<div>` на 123 строчке на `<form>`

2023-10-03 22:03 UTC, f4lz commented on index.html
> +               <ul class="footer-nav">
`footer__nav`

2023-10-03 22:03 UTC, f4lz commented on index.html
> +            <ul class="footer-nav d-flex align-items-center">
Тоже самое

2023-10-04 10:34 UTC, Bo4kaa commented on index.html
> +            <div class="container-info">
у меня есть info уже

2023-10-04 11:58 UTC, f4lz requested changes

2023-10-04 11:58 UTC, f4lz commented on .md
не,я же написал как сделать

2023-10-04 13:35 UTC, Bo4kaa commented on css/style.css
> +    margin-bottom: 116px;
+

2023-10-04 13:35 UTC, Bo4kaa commented on index.html
> +            <div class="container-info">
+

2023-10-04 13:35 UTC, Bo4kaa commented on index.html
> +                        <button class="btn-info">Gear</button>
+

2023-10-04 13:35 UTC, Bo4kaa commented on index.html
>                      <div class="promo-text">
+

2023-10-04 13:36 UTC, Bo4kaa commented on index.html
>              <img class="promo-img" src="img/promo-negr.png" alt="Negr">
+

2023-10-04 13:36 UTC, Bo4kaa commented on index.html
>                  <p>He’s here to help you level up your game by sharing everything he’s learned along the way.</p>
+

2023-10-04 13:37 UTC, Bo4kaa commented on index.html
>              </div>
+

2023-10-04 13:37 UTC, Bo4kaa commented on index.html
> +               <ul class="footer-nav">
+

2023-10-04 13:37 UTC, Bo4kaa commented on index.html
> +            <ul class="footer-nav d-flex align-items-center">
+

2023-10-04 13:37 UTC, Bo4kaa commented on .md
ты сука

2023-10-04 15:19 UTC, f4lz approved these changes

2023-10-04 15:19 UTC, merged